### ISSUE TITLE
define your own date format

### ISSUE THREAD

**Issue by samhuntsocial** [shinnn/calendar-date-regex#1]
nice module. thanks. 

would be nice to define own regex formats. such as Nov 22, 2014.

**Comment by shinnn** [comment]
@samhuntsocial 

I want this module to support for only [ISO 8601 calendar dates](http://en.wikipedia.org/wiki/ISO_8601#Calendar_dates). If you want to create other regex, maybe these modules meets your requirements:
- https://github.com/regexps/regex-utc-date
- https://github.com/regexps/regex-iso-date

Otherwise, I recommend you to create your own regex module.

I'm glad you like this module. Thanks :smiley:

**Comment by samhuntsocial** [comment]
Hi, yes I did look into those other 2 modules, but it didn't seem to help with my use case. 

I just used vanilla javascript regex to do the job to match "MMM DD, YYYY" date formats (e.g. Jun 12, 1999):

``` javascript
var pattern = /(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\ (([0-9])|([0-2][0-9])|([3][0-1]))\, \d{4}/mg;
var string = "Hello ignore here Jun 12, 1999 Also ignore the stuff here";
var result = pattern.exec(string);
console.log(result[0]); // output Jun 12, 1999
```

But of course not sure about the performance of doing this for **thousands** of records....

Cheers!
